version: "3"

services:
  snippetbox-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 8082:5432
    volumes:
      - snippetbox-postgres:/var/lib/postgresql/data

  snippetbox-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nowhere.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8081:80
    volumes:
        - snippetbox-pgadmin:/var/lib/pgadmin
    depends_on:
      - snippetbox-db

volumes:
  snippetbox-postgres:
  snippetbox-pgadmin: